### ISSUE TITLE
2015-10-30 Wikipedia image size is too big.

### ISSUE THREAD

**Issue by beaunus** [beaunus/dejaview#89]

**Comment by beaunus** [comment]
Something to do with OGV type

**Comment by xzjia** [comment]
It turned out that it's because we are treating some links ended with `ogv` as an image, which should be treated as a video. Following are the things that have been done:
- Under help of @SQLMD, figured out the existing file extension of `image_link` in the database.
- For extensions can't be explained, or too hard to be explained, like `.wav`, `.pdf`
    - Replace those links with empty in the database.
    - In the scraper project, filter those extension so they won't go into database at the first place.
- For those videos that are wrongly explained as images, like `ogg`, `ogv`
    - Copy those links to `media_link` column
    - In the scraper project, detect those links and add them into `media_link` column at the first place.
